- hosts: routers
  remote_user: ec2-user
  become: true

  tasks:
  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
      gpgcheck: no
  - name: Install qpid
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
       - qpid-dispatch-router
       - qpid-dispatch-tools
       - qpid-dispatch-docs
